# .pre-commit-config.yaml
- repo: https://github.com/psf/black
  rev: 22.3.0  # Choose the version of black
  hooks:
    - id: black
      language_version: python3  # Specify the Python version if needed

- repo: https://gitlab.com/pycqa/flake8
  rev: 4.0.1  # Choose the version of flake8
  hooks:
    - id: flake8
      language_version: python3  # Specify the Python version if needed
